<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://pk1" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://pk1" xmlns:intf="http://pk1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="HelloImpl">

   </wsdl:portType>

   <wsdl:binding name="HelloImplSoapBinding" type="impl:HelloImpl">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="HelloImplService">

      <wsdl:port binding="impl:HelloImplSoapBinding" name="HelloImpl">

         <wsdlsoap:address location="http://localhost:8080/SOAP_demo/services/HelloImpl"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
